nwf_policy_name: "prod-core-network-firewall-policy"

rule_groups:
  - name: "GLOBAL_ALLOW"
    allowed-domains:
     - ".releases.hashicorp.com"
     - ".s3.dualstack.eu-central-1.amazonaws.com"
     - ".pypi.org"
     - ".login.microsoftonline.com"
    source: "10.129.0.0/16"
    
  - name: "APPSTREAM"
    allowed-domains:
    # Microsoft 
     - ".windows.net" 
     - ".microsoft.com"
     - ".login.live.com"
     - ".msauthimages.net"
     - ".aka.ms"
     - ".office.com"
     - ".cdn.office.net"
     - ".autologon.microsoftazuread-sso.com"
     - ".login.microsoftonline.com"
     - ".activedirectory.windowsazure.com"
     - ".portal.azure.com"
     - ".msauth.net"
     - ".msftauth.net"
     - ".msftimages.net"
     # Amazon AWS
     - ".d-99671859b9.awsapps.com"
     - ".console.awsstatic.com"
     - ".aws.a2z.com"
     - ".support.aws.dev"
     - "portal.sso.eu-central-1.amazonaws.com"
     - "portal.sso.eu-west-1.amazonaws.com"
     - "static.global.sso.amazonaws.com"
     - ".signin.aws"
     - ".cloudfront.net"
     - ".amazonaws.com"
     - ".aws.amazon.com"
     # Developers
     - ".dev.azure.com"
     - ".githubassets.com"
     - ".github.com"
     - ".vscodeexperiments.azureedge.net"
     - ".vscode-cdn.net"
     - ".visualstudio.com"
     - ".gallery.vsassets.io"
     - ".gallerycdn.vsassets.io"
     - ".rink.hockeyapp.net"
     - ".bingsettingssearch.trafficmanager.net"
     - ".vsmarketplacebadge.apphb.com"
     - ".az764295.vo.msecnd.net"
     - ".vscode-sync.trafficmanager.net"
     - ".vscode-sync-insiders.trafficmanager.net"
     - ".vscode.dev"
     - ".github.dev"
     - ".vscode-unpkg.net"
     - ".default.exp-tas.com"
     - "pypi.org"
     - ".pstmn.io"
     - ".postman.com"
     - ".eclipse.org"
     - ".nodejs.org"
     - ".jetbrains.com"
     - ".githubusercontent.com"
     # Data Builders
     - ".snowflakecomputing.com"
     - ".getdbt.com"
     - ".rivery.io"
     # Security 
     - ".cas.ms"
     - ".mcas.ms"
     - ".admin-mcas.ms"
     - ".mcasproxy.azureedge.net"
     # Cloud Operations 
     - ".apps.cloudhealthtech.com"
     - ".vmware.com"
     - ".allcloud.io"
     # Browsing for end users
     - ".google.com"
     - ".googleusercontent.com"
     - ".mozilla.com"
     - ".mozilla.org"
     - ".tackle.io"
     - ".stripe.com"
     - ".launchdarkly.com"
     - ".googletagmanager.com"
     - "cdn.jsdelivr.net"
     - ".zdassets.com"
     - ".google-analytics.com"
     - ".gstatic.com"
     - ".zendesk.com"
     - ".cloud.typography.com"
     - ".cdn.cookielaw.org"
     - ".cloudflare.com"
     - ".googleapis.com"
    source: ["10.129.80.0/24","10.129.100.0/24"]


